packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - argon2
  - esbuild

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - "@fiatlux/*"
allowBuilds:
  argon2: true
  esbuild: true

overrides:
  "workbox-build>glob": 11.1.0
