#!/usr/bin/env bash

# These allowlists describe the exact runtime capability surface of the long-lived
# application containers. Keep secrets used only by bootstrap, migration, backup,
# restore, or seed jobs out of these expressions.
# shellcheck disable=SC2034 # This file is sourced by verifiers and focused tests.
API_RUNTIME_ENVIRONMENT_ALLOWLIST='^(PATH|NODE_VERSION|YARN_VERSION|NODE_ENV|API_HOST|API_PORT|WEB_ORIGIN|DATABASE_URL|DATABASE_POOL_SIZE|DATABASE_CONNECT_TIMEOUT_SECONDS|READINESS_TIMEOUT_MS|JWT_SECRET|JWT_TTL_SECONDS|COOKIE_SECURE|MFA_ENCRYPTION_KEY|MFA_ENCRYPTION_KEY_ID|MFA_REQUIRED_ROLES|MFA_CHALLENGE_TTL_SECONDS|MFA_SETUP_TTL_SECONDS|S3_ENDPOINT|S3_REGION|S3_BUCKET|S3_ACCESS_KEY_ID|S3_SECRET_ACCESS_KEY|LLM_DRIVER|LLM_BASE_URL|LLM_PROVIDER_ID|LLM_MODEL|LLM_MAX_OUTPUT_TOKENS|GITHUB_INTEGRATION_MODE|TRUST_PROXY)$'
# shellcheck disable=SC2034 # This file is sourced by verifiers and focused tests.
WORKER_RUNTIME_ENVIRONMENT_ALLOWLIST='^(PATH|NODE_VERSION|YARN_VERSION|NODE_ENV|DATABASE_URL|DATABASE_POOL_SIZE|DATABASE_CONNECT_TIMEOUT_SECONDS|COMPLIANCE_MONITOR_SWEEP_BATCH_SIZE|LLM_DRIVER|LLM_BASE_URL|LLM_API_KEY|LLM_PROVIDER_ID|LLM_MODEL|LLM_MAX_OUTPUT_TOKENS|GITHUB_INTEGRATION_MODE|GITHUB_TOKEN|GITHUB_PROBE_REPOSITORY|BACKUP_COMMAND|BACKUP_DIR|PGHOST|PGPORT|PGDATABASE|PGUSER|PGPASSWORD|BACKUP_AGE_RECIPIENT|BACKUP_REQUIRE_ENCRYPTION)$'
