#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)
# shellcheck source=scripts/lib/runtime-environment-allowlists.sh
source "$ROOT_DIR/scripts/lib/runtime-environment-allowlists.sh"

assert_allowed() {
  local expression=$1
  shift
  local name
  for name in "$@"; do
    if ! grep -Eq "$expression" <<<"$name"; then
      printf '应允许的运行时变量被拒绝：%s\n' "$name" >&2
      exit 1
    fi
  done
}

assert_rejected() {
  local expression=$1
  shift
  local name
  for name in "$@"; do
    if grep -Eq "$expression" <<<"$name"; then
      printf '一次性或越权变量被运行时白名单接受：%s\n' "$name" >&2
      exit 1
    fi
  done
}

assert_allowed "$API_RUNTIME_ENVIRONMENT_ALLOWLIST" \
  PATH NODE_VERSION YARN_VERSION NODE_ENV API_HOST API_PORT WEB_ORIGIN \
  DATABASE_URL DATABASE_POOL_SIZE DATABASE_CONNECT_TIMEOUT_SECONDS \
  READINESS_TIMEOUT_MS JWT_SECRET JWT_TTL_SECONDS COOKIE_SECURE \
  MFA_ENCRYPTION_KEY MFA_ENCRYPTION_KEY_ID MFA_REQUIRED_ROLES \
  MFA_CHALLENGE_TTL_SECONDS MFA_SETUP_TTL_SECONDS S3_ENDPOINT S3_REGION \
  S3_BUCKET S3_ACCESS_KEY_ID S3_SECRET_ACCESS_KEY LLM_DRIVER LLM_BASE_URL \
  LLM_PROVIDER_ID LLM_MODEL LLM_MAX_OUTPUT_TOKENS GITHUB_INTEGRATION_MODE \
  TRUST_PROXY
assert_rejected "$API_RUNTIME_ENVIRONMENT_ALLOWLIST" \
  INITIAL_ADMIN_PASSWORD POSTGRES_BOOTSTRAP_PASSWORD POSTGRES_MIGRATION_PASSWORD \
  POSTGRES_BACKUP_PASSWORD POSTGRES_RESTORE_PASSWORD LLM_API_KEY GITHUB_TOKEN \
  BACKUP_SIGNING_PRIVATE_KEY_FILE

assert_allowed "$WORKER_RUNTIME_ENVIRONMENT_ALLOWLIST" \
  PATH NODE_VERSION YARN_VERSION NODE_ENV DATABASE_URL DATABASE_POOL_SIZE \
  DATABASE_CONNECT_TIMEOUT_SECONDS COMPLIANCE_MONITOR_SWEEP_BATCH_SIZE \
  LLM_DRIVER LLM_BASE_URL LLM_API_KEY LLM_PROVIDER_ID LLM_MODEL \
  LLM_MAX_OUTPUT_TOKENS GITHUB_INTEGRATION_MODE GITHUB_TOKEN \
  GITHUB_PROBE_REPOSITORY BACKUP_COMMAND BACKUP_DIR PGHOST PGPORT PGDATABASE \
  PGUSER PGPASSWORD BACKUP_AGE_RECIPIENT BACKUP_REQUIRE_ENCRYPTION
assert_rejected "$WORKER_RUNTIME_ENVIRONMENT_ALLOWLIST" \
  JWT_SECRET MFA_ENCRYPTION_KEY MFA_ENCRYPTION_KEY_ID MFA_REQUIRED_ROLES \
  S3_SECRET_ACCESS_KEY INITIAL_ADMIN_PASSWORD POSTGRES_BOOTSTRAP_PASSWORD \
  POSTGRES_MIGRATION_PASSWORD POSTGRES_BACKUP_PASSWORD POSTGRES_RESTORE_PASSWORD \
  BACKUP_SIGNING_PRIVATE_KEY_FILE

echo "运行时环境变量最小权限白名单测试通过。"
